name: anki-desktop
base: core24
version: '25.09.2'
license: AGPL-3.0-or-later
summary: Anki is a spaced repetition program
description: |
  Anki is a program which makes remembering things easy. Because it's a lot more efficient than traditional study methods, you can either greatly decrease your time spent studying, or greatly increase the amount you learn.

  Anyone who needs to remember things in their daily life can benefit from Anki. Since it is content-agnostic and supports images, audio, videos and scientific markup (via LaTeX), the possibilities are endless.
  For example:

  - Learning a language
  - Studying for medical and law exams
  - Memorizing people's names and faces
  - Brushing up on geography
  - Mastering long poems
  - Even practicing guitar chords!
platforms:
  amd64:
  arm64:
grade: stable
confinement: strict
compression: lzo

apps:
  anki-desktop:
    command: ./bin/anki
    desktop: meta/gui/anki-desktop.desktop
    environment:
      ANKI_BASE: $SNAP_USER_COMMON
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.12/site-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack
      QTWEBENGINE_DISABLE_SANDBOX: 1
      # DISABLE_WAYLAND: 1
    extensions:
      - kde-neon-6
    plugs:
      - audio-record
      - browser-support
      - home

parts:
  anki:
    plugin: python
    source: .
    python-packages:
      - aqt==${SNAPCRAFT_PROJECT_VERSION}
      - anki==${SNAPCRAFT_PROJECT_VERSION}
    stage-packages:
      - libnss3
      - lame
      - mpv
    prime:
      - -lib/python3.12/site-packages/PyQt6/Qt6/
